name: ci

on:
  push:
    branches: [main]
    paths:
      - "services/**"
      - "buildspec.yml"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout apps-sre
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: vars
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "tag=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "image=770132776547.dkr.ecr.us-east-1.amazonaws.com/shopstack-catalog:$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "Image: 770132776547.dkr.ecr.us-east-1.amazonaws.com/shopstack-catalog:$SHORT_SHA"

      - name: Build Docker image
        run: |
          docker build \
            -t "${{ steps.vars.outputs.image }}" \
            -t "770132776547.dkr.ecr.us-east-1.amazonaws.com/shopstack-catalog:latest" \
            services/catalog

      - name: Push to ECR
        run: |
          docker push "${{ steps.vars.outputs.image }}"
          docker push "770132776547.dkr.ecr.us-east-1.amazonaws.com/shopstack-catalog:latest"

      - name: Get GitHub token from Secrets Manager
        id: github-token
        run: |
          TOKEN=$(aws secretsmanager get-secret-value \
            --secret-id shopstack/dev/github-token \
            --query SecretString \
            --output text \
            --region us-east-1)
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Update GitOps and open PR
        run: |
          SHORT_SHA="${{ steps.vars.outputs.tag }}"
          FULL_SHA="${{ github.sha }}"
          BRANCH="chore/catalog-image-${SHORT_SHA}"

          git config --global url."https://${{ steps.github-token.outputs.token }}@github.com/".insteadOf "https://github.com/"
          git config --global user.email "ci@shopstack"
          git config --global user.name "ShopStack CI"

          cd /tmp
          git clone https://github.com/juandiegocv27/cluster-gitops.git
          cd cluster-gitops

          git checkout -b "$BRANCH"
          sed -i "s/^\(\s*newTag:\s*\).*/\1\"${FULL_SHA}\"/" \
            apps/catalog/overlays/dev/kustomization.yaml

          echo "Git diff:"
          git diff

          git add apps/catalog/overlays/dev/kustomization.yaml
          git commit -m "chore: bump catalog image to ${SHORT_SHA}"
          git push origin "$BRANCH"

          echo "Branch pushed: $BRANCH"
